### ISSUE TITLE
java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by espiegel** [mcxiaoke/android-volley#37] opened 2015-01-29 10:25 UTC
I'm getting this error sometimes which causes my application to crash:

java.lang.NegativeArraySizeException: -450
            at com.android.volley.toolbox.DiskBasedCache.streamToBytes(DiskBasedCache.java:322)
            at com.android.volley.toolbox.DiskBasedCache.get(DiskBasedCache.java:118)
            at com.android.volley.CacheDispatcher.run(CacheDispatcher.java:100)

**Comment by mcxiaoke** [comment] 2015-03-19 04:15
fixed in https://github.com/mcxiaoke/android-volley/pull/38

**Closed by mcxiaoke** 2015-03-19 04:15 UTC

**Comment by ValleZ** [comment] 2015-04-27 17:29
is this in 1.0.15?

**Comment by mcxiaoke** [comment] 2015-04-29 03:23
@ValleZ No, I will release a new version in two days.

**Comment by mcxiaoke** [comment] 2015-04-29 03:24
@ValleZ not yet, I will publish a new version in this week.

**Comment by moradgholi** [comment] 2015-05-17 12:56
@mcxiaoke haven't you release an update on this ?

**Comment by mcxiaoke** [comment] 2015-05-18 04:37
@moradgholi released today

**Comment by binqiangsun** [comment] 2015-06-01 06:11
Is this only github updated. I found these codes are not in the android / platform/frameworks/volley / android-5.1.1_r4  of google code?

**Comment by joebowbeer** [comment] 2016-10-04 02:17
I think this is another symptom of #61 (OutOfMemoryError) and both of these are caused by problems reading the header.

**Comment by agozie** [comment] 2017-01-28 08:53
I got this today.

Exception java.lang.NegativeArraySizeException: -824
com.android.volley.toolbox.DiskBasedCache.streamToBytes (DiskBasedCache.java:323)
com.android.volley.toolbox.DiskBasedCache.get (DiskBasedCache.java:119)
com.android.volley.CacheDispatcher.run (CacheDispatcher.java:100)

**Comment by abhaymaniyar** [comment] 2018-01-06 13:26
I got this few days ago:

Fatal Exception: java.lang.NegativeArraySizeException: -1362
       at com.android.volley.toolbox.DiskBasedCache.streamToBytes(DiskBasedCache.java:323)
       at com.android.volley.toolbox.DiskBasedCache.get(DiskBasedCache.java:119)
       at com.android.volley.CacheDispatcher.run(CacheDispatcher.java:100)

**Comment by joebowbeer** [comment] 2018-01-06 13:52
This should now be fixed in the 1.1.1-SNAPSHOT build of https://github.com/google/volley
