### ISSUE TITLE
API request sent two times

### ISSUE THREAD

**Issue by joydip1990** [mcxiaoke/android-volley#76] opened 2015-07-23 14:21 UTC
Server is slow. Volley is sending request two times i.e Its retrying to send request again.

I had solved the problem by overriding  retry policy.

 jsonObjReq.setShouldCache(false);

 jsonObjReq.setRetryPolicy(new DefaultRetryPolicy(
                (int) TimeUnit.SECONDS.toMillis(20),
                DefaultRetryPolicy.DEFAULT_MAX_RETRIES,
                DefaultRetryPolicy.DEFAULT_BACKOFF_MULT));

Please resolve this issue.

**Comment by mcxiaoke** [comment] 2015-07-27 12:29
duplicate of issue #46

**Closed by mcxiaoke** 2015-07-27 12:29 UTC
